### ISSUE TITLE
MSP430F5529 : String(uint16_t) fails

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp430-ng-core#3]
Result for `String()` is 

> 12345    @

instead of 

> 12345    12345
- Code

```
void setup() 
{
  // put your setup code here, to run once:
  Serial.begin(9600);
  delay(600);
  Serial.println("***");

  uint16_t value = 12345;

  Serial.print(value, DEC);
  Serial.print("\t");
  Serial.println(String(value));
}


void loop() 
{

}
```

**Comment by rei-vilo** [comment]
`String(float, precision)`  `dtostrf()` seem to be affected as well. 

See [String(float, precision) & dtostrf() bug](http://forum.43oh.com/topic/9865-stringfloat-precision-dtostrf-bug/).

**Comment by robertinant** [comment]
This issue was moved to energia/msp430-lg-core#43
